### ISSUE TITLE
Unit Test Fails on IAM Policy Condition Elements

### ISSUE THREAD

**Issue by aharshbarger** [DontShaveTheYak/cloud-radar#178]
A unit test fails to load a CFN template that defines a `AWS::KMS::Key` Resource that contains a `KeyPolicy::Statement` with a [Condition](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition.html).    

The CFN template functions as expected when deployed to AWS with the condition syntax below.

```
Resources:
  SampleKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Sample-Key
      Enabled: True
      KeyPolicy:
        Version: 2012-10-17
        Id: key-default-1
        Statement:
          - Sid: Allow attachment of persistent resources
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling
            Action:
              - "kms:CreateGrant"
            Resource: "*"
            Condition:
              "Bool":
                "kms:GrantIsForAWSResource": "true"
```

cloud-radar version: `0.6.3`
python version: `3.10.9`

Basic Unit test snippet:
```
    template: Template = request.getfixturevalue(templ_fix)
    stack = template.render(region = "us-west-2")

    assert "SampleKey" in stack["Resources"]
```

![image](https://user-images.githubusercontent.com/15339361/219375812-d58a64f1-275e-408e-90fd-ecfebdc979ba.png)
