### ISSUE TITLE
Dynamic References

### ISSUE THREAD

**Issue by dhutchison** [DontShaveTheYak/cloud-radar#220]
First off - it is good to see something that can move testing of CloudFormation closer to unit testing, and this seems nice & clean for that purpose :)

Now on to the issue - I've been doing a quick PoC on using this to compare against resource naming conventions that we use and hit a stumbling block. We make use of [Dynamic References](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html) as a component in many of our names, and these do not get resolved in the stack creation part of a unit test. 

As an example, we have an SSM parameter deployed into our accounts for `/account/current/short_name` which contains a short name for the current account (so if our account 5555555555 was called "Deployment - Production" this ssm parameter would resolve to "dep-prd"). 

So we would have a resource like this:

```
rServiceCatalogProductLaunchRolePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: 'mgt-{{resolve:ssm:/account/current/short_name}}-infra-ci-cd-product-launch-role-pol'
```

In a unit test this PolicyName property still contains the `{{resolve...` block. 

I guess I have two questions:

1. Is this a gap / issue that should be fixed, or is the current behaviour intended?
2. If it should be fixed, would a configuration approach like is currently used for imports be suitable? Taking in the type (ssm/secret etc), key and value?
