### ISSUE TITLE
Allow Fn::Split and Fn::Transform to be nested within Fn::If

### ISSUE THREAD

**Issue by robgodfrey** [DontShaveTheYak/cloud-radar#406]
Hi

I bumped into a couple of cloudformation examples which aren't supported by cloud_radar. 

**Scenario 1: Fn::Split nested within Fn::If**

```yaml
...

Conditions:
  ConfigureContainerCommand: !Not [!Equals [!Ref ContainerCommand, ""]]

Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - ...
          Command: !If
            - ConfigureContainerCommand
            - !Split [" ", !Ref ContainerCommand]
            - !Ref "AWS::NoValue"
```

When template.create_stack() is invoked a ValueError is raised 

```
    
                if key not in allowed_func:
>                   raise ValueError(f"{key} with value ({value}) not allowed here")
E                   ValueError: Fn::Split with value ([' ', {'Ref': 'ContainerCommand'}]) not allowed here

venv/lib/python3.10/site-packages/cloud_radar/cf/unit/_template.py:382: ValueError
```

**Scenario 1: Fn::Transform nested within Fn::If**

Example cfn config 
```yaml
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ...
      ContainerDefinitions
         - ...
            Secrets: !If
            - ConfigureContainerSecrets
            - Fn::Transform:
                Name: 'UnpackEcsContainerSecretsMacro'
                Parameters:
                  ContainerSecretArn: !Ref ContainerSecretsArn
            - !Ref "AWS::NoValue"
```

Similar to above a value error is raised this time flagging Fn::Transform as not allowed. 

**Workaround:** 

I have patched functions.ALLOWED_FUNCTIONS as follows to workaround this limitation:

```python
from cloud_radar.cf.unit import Template, functions
from unittest.mock import patch


def process_template(params, imports):

    # Patch cloud_radar to allow Fn::Transform and Fn::Split functions to be nested within Fn::If
    with patch.dict(functions.ALLOWED_FUNCTIONS, {"Fn::If": {"Fn::Transform": functions.transform, "Fn::Split": functions.split}}):
        template = Template.from_yaml("templates/public-load-balanced-web-service.yaml", imports=imports)
        return template.create_stack(params=params, region="eu-west-1")
```
