### ISSUE TITLE
Support !Select when the array of elements is a !Split on !Ref

### ISSUE THREAD

**Issue by gmarciani** [DontShaveTheYak/cloud-radar#414]
Hello,

this project is great, but I'm facing a blocker, which I need help for.

I'm using cloud-radar pointing to this commit https://github.com/DontShaveTheYak/cloud-radar/commit/648bc29e0b2ba006872c899a5962cd9228749ac6 (it contains a fix I needed).

The following template:

```
Resources:
  DummyEcrImage:
    Type: AWS::ImageBuilder::Image
    Properties:
      ContainerRecipeArn: "ContainerRecipeArn"
      EnhancedImageMetadataEnabled: true
      InfrastructureConfigurationArn: "InfrastructureConfigurationArn"
      ImageTestsConfiguration:
        ImageTestsEnabled: false

  DummyParameter1:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !Select [2, !Split ['/', !Ref DummyEcrImage]]
```

returns the following error when `template.create_stack()` is called:

```
        try:
            return items[index]
        except IndexError:
>           raise IndexError(
                "Fn::Select - List size is smaller than the Index given."
            ) from None
E           IndexError: Fn::Select - List size is smaller than the Index given.
```

May you please support this use case?

Thank you,
Giacomo
