### ISSUE TITLE
Support nested !Select

### ISSUE THREAD

**Issue by gmarciani** [DontShaveTheYak/cloud-radar#415]
Hello,

this project is great, but I'm facing a blocker, which I need help for.

I'm using cloud-radar pointing to this commit https://github.com/DontShaveTheYak/cloud-radar/commit/648bc29e0b2ba006872c899a5962cd9228749ac6 (it contains a fix I needed).

The following template:

```
Resources:
  DummyNestedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://myendpoint/mytemplate.yaml"

  DummyParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !Select [2, !Split ['/', !Select [0, !Split ['.', !GetAtt [ DummyNestedStack, Outputs.DummyOutput ]]]]]
```

returns the following error when `template.create_stack()` is called:

```
        try:
            return items[index]
        except IndexError:
>           raise IndexError(
                "Fn::Select - List size is smaller than the Index given."
            ) from None
E           IndexError: Fn::Select - List size is smaller than the Index given.
```

Notice that a slightly different template succeeds the creation:

```
Resources:
  DummyNestedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://myendpoint/mytemplate.yaml"

  DummyParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !Select [ 0, !Split [ '.', !GetAtt [ DummyNestedStack, Outputs.DummyOutput ] ] ]
```

so I guess the problem is around nesting !Select

May you please support this use case?

Thank you,
Giacomo
